### ISSUE TITLE
返回后会在上一个界面add 一个view 导致界面过度绘制

### ISSUE THREAD

**Issue by jiantao88** [oubowu/SlideBack#10]
进入一个界面，然后滑动返回，上一个界面过度绘制会变红，请问能解决这个问题么？

**Comment by oubowu** [comment]
这个我也不是很明白为什么过渡绘制，我在滑动界面滑动的时候会把上个页面的布局添加到底部；滑动回去又添加回去，没对这个页面做过什么处理，不知道为什么会过渡绘制了
