### ISSUE TITLE
希望作者能上传jcenter，对这个库很感兴趣，希望能共同帮助维护

### ISSUE THREAD

**Issue by AcgnCodeMonkey** [oubowu/SlideBack#12]
如题。今天找了滑动返回的库找了很久，大部分都是基于swipeBackLayout做的，必须要设置透明主题，但是透明主题会引起各种bug，终于找到作者这个不用设置透明主题的了。大概看了下源码，觉得思路还是比较好的，希望能上传jcenter

**Comment by oubowu** [comment]
这个库只能是实验性的，对屏幕旋转后toolbar支持不好，如果你想维护的话其实可以fork一份进行修改，再提交给我
