### ISSUE TITLE
当activity有倒计时控件时，界面滑动会不停闪烁，怎么解

### ISSUE THREAD

**Issue by gndegithub** [oubowu/SlideBack#13]

**Comment by oubowu** [comment]
建议在滑动的监听那里把他停止倒计时

**Comment by gndegithub** [comment]
这种方式只能暂停当前页的倒计时，比如我首页有个倒计时，但是没做滑动处理。这个倒计时还影响了所以二级页面的滑动效果，总之这块挺复杂，这咋整？望指导一下~可以的话加下我qq 813196526。多谢多谢

**Comment by oubowu** [comment]
这种倒计时的东西不能在页面不可见的时候暂停吗 其实这种不断更新页面的控件 在不可见的时候最好做下暂停的处理

**Comment by gndegithub** [comment]
现在就是改为暂停的，不过有些地方不好改动。弱弱的问下，这种框架是不是遇到倒计时 定时更新 间隔滚动等都不能很好的处理？
就针对这个问题，有没有类似的框架能解决

**Comment by oubowu** [comment]
是的 因为这些定时更新ui的会重新跑layout一遍 会导致他layout回原处 所以要你自己自定义viewgroup的layout流程 这样子就更麻烦了

**Comment by gndegithub** [comment]
还有一个问题，我时不时会遇到，滑动返回，上级页面onResume里面的view逻辑会出现空指针是何原因？
