### ISSUE TITLE
导入之后发现底部存在存在一个黑色栏

### ISSUE THREAD

**Issue by yugai** [oubowu/SlideBack#2]
如题

**Comment by oubowu** [comment]
可否贴个图，没图不知道咋回事 @yugai

**Comment by yugai** [comment]
![device-2016-10-26-215417](https://cloud.githubusercontent.com/assets/8723944/19728787/497deea4-9bc7-11e6-8cc4-61ff1214332c.png)

**Comment by oubowu** [comment]
用在了其他项目？手机型号是啥？是不是有虚拟按键 @yugai 或者直接加我qq 377793729 我看看什么问题

**Comment by yugai** [comment]
这个是为了测试和5.0动画是否有冲突。  所以导入到https://github.com/lgvalle/Material-Animations这个项目中试用了下。   手机是红米note3.  没有虚拟按键。

**Comment by oubowu** [comment]
好的 多谢 @yugai

**Comment by oubowu** [comment]
问题知道出在哪了，应该是动画还未执行完就attach到滑动布局了，在onWindowFocusChanged这时候初始化再去attach它就没问题了，剩下的还有状态栏颜色问题是个大坑
`

```
@Override
public void onWindowFocusChanged(boolean hasFocus) {
    super.onWindowFocusChanged(hasFocus);
    if (hasFocus && slideBackLayout == null) {
        slideBackLayout = SlideBackHelper.attach(this, MyApplication.getActivityHelper(),
                new SlideConfig.Builder().rotateScreen(true).edgeOnly(false).lock(false).edgePercent(0.1f).slideOutPercent(0.5f).create(), null);
    }
}
```

`

**Comment by oubowu** [comment]
@yugai

**Comment by yugai** [comment]
恩 已看。 滑动返回在Android上确实是个坑，设置透明背景思路简单但会失去原有属性。不设置背景坑更多了。加油吧。

**Comment by oubowu** [comment]
实验性的项目，抛开实用性不说，最重要是换一种思路解决问题，即使达不到效果也能从中涨不少知识，过程也很重要，我是这样想的 @yugai

**Comment by yugai** [comment]
恩 我自己也在寻求一种 最合适的滑动返回库。  目前发现的最好的就是不用拖动动画，判断手势返回。  这种能达到简单的易用性。同时能够丝毫不影响其他功能，例如Activity共享动画。但是不够完美主义。 当然很庆幸有一群能够研究并开源的人。

**Comment by oubowu** [comment]
IOS自带这东西，安卓虽说有返回键，但是这个功能对大屏幕真是很实用，如果微信能开源就好了，估计微信做的相当好
