### ISSUE TITLE
边缘长按有时会闪回去

### ISSUE THREAD

**Issue by JakeWoki** [oubowu/SlideBack#4]
在SecondActivity界面的，跳转侧滑页面按钮左下边缘，滑动一下放开，再长按滑动（不行可多操作几次），界面会突然闪回去

**Comment by oubowu** [comment]
我知道原因了，它响应了上个页面的点击事件，容我处理处理

**Comment by oubowu** [comment]
已经解决了，你pull下代码测一下 @JakeWoki
