### ISSUE TITLE
边缘斜向上侧滑可以不让它返回吗

### ISSUE THREAD

**Issue by lcl6** [oubowu/SlideBack#5]

**Comment by oubowu** [comment]
不行，虽然是斜向上，但是它水平滑动发生了，你可以看下微信也是这样的 @chenlindaydayup

**Comment by lcl6** [comment]
uc的侧滑返回时怎么做的呢  uc就可以

**Comment by oubowu** [comment]
uc应该是自己处理了滑动的事件，保证滑动的y方向的偏移量在一定的阈值内才响应滑动返回，而我是用viewdraghelper处理的滑动事件，它只要你有水平偏移量就响应了，不管你的垂直偏移量 @chenlindaydayup
